version: "3"
services:
  api:
    image: ml-game-api
    build: 
      context: .
      args:
        - DATABASE_URL=${DATABASE_URL:-postgresql://user:password@localhost:5432/mydb?schema=public}
    networks:
      - backend
    ports:
      - "6001:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}

networks:
  backend:
    driver: bridge
